"use client";

import { useCallback, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ChevronDown, Plus, Search } from "lucide-react";
import { AppSidebar } from "@/components/app-sidebar";
import {
  SidebarProvider,
  SidebarInset,
  SidebarTrigger,
} from "@/components/ui/sidebar";

const fileTypes = ["All", "Website", "Document", "Excel", "PPT", "Image", "Video", "Audio"];
const sources = ["From Agent", "From You"];

export default function StoragePage() {
  const [activeType, setActiveType] = useState("All");
  const [activeSource, setActiveSource] = useState("From Agent");
  const [sourceOpen, setSourceOpen] = useState(false);
  const [search, setSearch] = useState("");
  const dropdownRef = useRef<HTMLDivElement>(null);
  const router = useRouter();

  const handleNewAgent = useCallback(() => {
    const sessionId = crypto.randomUUID();
    router.push(`/?session=${sessionId}`);
  }, [router]);

  const handleSelectSession = useCallback(
    (sessionId: string) => {
      router.push(`/?session=${sessionId}`);
    },
    [router],
  );

  return (
    <SidebarProvider defaultOpen={false} className="h-[100dvh] overflow-hidden">
      <AppSidebar
        onNewAgent={handleNewAgent}
        onSelectSession={handleSelectSession}
      />
      <SidebarInset className="min-h-0 overflow-hidden">
        <header className="flex h-12 shrink-0 items-center px-4">
          <SidebarTrigger />
        </header>
        <main className="flex-1 overflow-y-auto px-6 pb-12">
          <h1 className="text-2xl font-bold mb-6">Assets</h1>

          <div className="flex items-center gap-4 mb-8">
            {/* Source dropdown */}
            <div className="relative" ref={dropdownRef}>
              <button
                onClick={() => setSourceOpen(!sourceOpen)}
                className="flex items-center gap-2 rounded-full border border-gray-200 px-4 py-2 text-sm font-medium text-gray-900 hover:bg-gray-50"
              >
                {activeSource}
                <ChevronDown className="h-4 w-4" />
              </button>
              {sourceOpen && (
                <div className="absolute left-0 top-full z-10 mt-1 w-40 rounded-lg border border-gray-200 bg-white py-1 shadow-lg">
                  {sources.map((source) => (
                    <button
                      key={source}
                      onClick={() => {
                        setActiveSource(source);
                        setSourceOpen(false);
                      }}
                      className="block w-full px-4 py-2 text-left text-sm text-gray-900 hover:bg-gray-50"
                    >
                      {source}
                    </button>
                  ))}
                </div>
              )}
            </div>

            {/* File type tabs */}
            <nav className="flex gap-4">
              {fileTypes.map((type) => (
                <button
                  key={type}
                  onClick={() => setActiveType(type)}
                  className={`text-sm font-medium transition-colors ${
                    activeType === type
                      ? "text-black"
                      : "text-gray-400 hover:text-black"
                  }`}
                >
                  {type}
                </button>
              ))}
            </nav>

            {/* Search */}
            <div className="ml-auto flex items-center gap-2 rounded-lg border border-gray-200 px-3 py-2">
              <Search className="h-4 w-4 text-gray-400" />
              <input
                type="text"
                placeholder="Search by file or task name"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="border-none bg-transparent text-sm text-gray-900 placeholder-gray-400 outline-none w-52"
              />
            </div>
          </div>

          {/* Empty state */}
          <div className="flex flex-col items-center justify-center py-32">
            <h2 className="text-lg font-bold text-gray-900">No assets yet</h2>
            <p className="mt-2 text-sm text-gray-500">
              Files generated by AI and uploaded by you will appear here
            </p>
            <button
              onClick={handleNewAgent}
              className="mt-6 flex items-center gap-2 rounded-lg bg-screamin-green-800 px-6 py-3 text-sm font-medium text-white hover:bg-screamin-green-700"
            >
              <Plus className="h-4 w-4" />
              New Task
            </button>
          </div>
        </main>
      </SidebarInset>
    </SidebarProvider>
  );
}
